apiVersion: v1
kind: Service
metadata:
  name: world-seed-discord
  labels:
    run: world-seed-discord
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: world-seed-discord
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-seed-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-seed-discord
  template:
    metadata:
      labels:
        app: world-seed-discord
    spec:
      containers:
        - name: world-seed-discord
          image: herrykun/world.seed.discord
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
           path: /data/world.seed.discord
      imagePullSecrets:
        - name: regcred
      nodeName: master
