---
apiVersion: v1
kind: Service
metadata:
  name: world-seed-server
  labels:
    run: world-seed-server
spec:
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30005
  selector:
    app: world-seed-server
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-seed-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-seed-server
  template:
    metadata:
      labels:
        app: world-seed-server
    spec:
      containers:
        - name: pointify-client
          image: herrykun/world.seed.server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: data
        - name: nginx-rerouter
          image: herrykun/nginx.rerouter
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /certs
              name: certs
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: longhorn-cert-claim
        - name: data
          persistentVolumeClaim:
            claimName: longhorn-worldseed-claim
---
apiVersion: v1
kind: Service
metadata:
  name: world-seed-discord
  labels:
    run: world-seed-discord
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: world-seed-discord
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-seed-discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world-seed-discord
  template:
    metadata:
      labels:
        app: world-seed-discord
    spec:
      containers:
        - name: world-seed-discord
          image: herrykun/world.seed.discord
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: longhorn-cert-claim
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-worldseed-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi