jwt:
  secret: IzSE2A5hlNetgD3XTooA
file:
  upload-dir: "data"
server:
  port: 80
springdoc:
  api-docs:
    path: "/docs"
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1024MB
      max-request-size: 1048MB
  datasource:
    url: "jdbc:mysql://test2.nope-api.systems:3306/world_seed?useSSL=false&amp;allowPublicKeyRetrieval=true"
    username: "sand"
    password: "llH5CqypeHfILgJjUmCS#"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5InnoDBDialect"
        ddl-auto: validate
        id:
          new_generator_mappings: false